name: continuous-integration-py

# This workflow is triggered by
on:
    # Run at least once a week
    schedule:
        - cron: '0 0 0 * *'
    # Any push to master
    push:
        branches:
            - master
    # Any pull request opened to master
    pull_request:
        branches:
            - master
    # Any release issued
    release:
        types:
            - created

jobs:
    # First job is to automatically generate the docs
    docbuild:
        # Job name
        name: DocBuild
        # Ok to just use ubuntu -- Don't need docs from multiple platforms
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./.github/actions/refresh_sphinx_docs
    # Second job is to run tests
    test:
        name: Test
        runs-on: [ubuntu-latest, mac-latest, windows-latest]


