name: continuous-integration-py

# This workflow is triggered by
on:
    # Run at least once a week
    # schedule:
    #     - cron: '0 0 0 * *'
    # Any push to master
    push:
        branches:
            - test_ga
    # Any pull request opened to master
    pull_request:
        branches:
            - master
    # Any release issued
    release:
        types:
            - created

jobs:
    # First job is to automatically generate the docs
    docbuild:
        # Job name
        name: DocBuild
        # Ok to just use ubuntu -- Don't need docs from multiple platforms
        runs-on: ubuntu-latest
        steps:
        - name: get_repo
          uses: actions/checkout@master
          with:
              ref: test_ga
        - name: installation
          run: |
              sudo apt-get install python3-pip python3 python3-sphinx python3-setuptools
              pip3 install -r requirements.txt
              pip3 install .
        - name: sphinx_docs
          run: |
              cd docs
              # rm -rf source
              # sphinx-apidoc -o source ../transcripty
              # cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1 >> newfile.txt
              touch newfile.txt
              # make html
              cd ..
        - name: commit
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add docs/newfile.txt
            git commit -m "Add changes"
        - name: push
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
    # Second job is to run tests
    # test:
    #     name: Test
    #     runs-on: [ubuntu-latest, mac-latest, windows-latest]


