name: test-hello-world

# This workflow is triggered by
on:
    # Any push to master
    push:
        branches:
            # - test_ga
            - master

jobs:
    # First job is to automatically generate the docs
    docbuild:
        # Job name
        name: DocBuild
        # Ok to just use ubuntu -- Don't need docs from multiple platforms
        runs-on: ubuntu-latest
        steps:
        # To use this repository's private action, you must check out the repository
        - name: Checkout
          uses: actions/checkout@v1
        - name: Hello world action step
          uses: ./.github/actions/hello-world
          id: hello
          with:
            who-to-greet: 'Mona the Octocat'
        # Use the output from the `hello` step
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
        - name: Get the sphinx version
          run: echo "The sphinx version was ${{ steps.hello.outputs.sphinx_version}}"

